### ISSUE TITLE
Frames do not write, display window absent. 

### ISSUE THREAD

**Issue by netrosec** [ahmetozlu/face_recognition_crop#1]
Hi Ahmet. I ran your code straight out the box on ubuntu 18.04 with all necessary prerequisite installed, it displayed this: 
```
Writing frame 1 / 7717
Writing frame 2 / 7717
Writing frame 3 / 7717
Writing frame 4 / 7717
Writing frame 5 / 7717
Writing frame 6 / 7717
Writing frame 7 / 7717
Writing frame 8 / 7717
Writing frame 9 / 7717
Writing frame 10 / 7717
Writing frame 11 / 7717
Writing frame 12 / 7717

```
but infact did not write the frames to system. No display windows showed without bounding box around faces either.

**Comment by ahmetozlu** [comment]
fixed, please check it again..
